# DEFINE -- Generated by Model Builder
# 2026-05-31 20:11

# -- Model Metadata (descriptions & sources) -------------------------------
# Read back by DEFINE app to pre-populate all input fields.
.var_descs <- list(
  "Y_H" = "Disposable income of households (USD trillion)",
  "W" = "Wage income (USD trillion)",
  "D" = "Deposits (USD trillion)",
  "Y" = "Output (USD trillion)",
  "TP" = "Total profits of firms (USD trillion)",
  "RP" = "Retained profits (USD trillion)",
  "DP" = "Distributed profits (USD trillion)",
  "r" = "Rate of profit",
  "I" = "Investment (USD trillion)",
  "I_G" = "Green investment (USD trillion)",
  "beta" = "Share of green investment in total investment",
  "I_C" = "Conventional investment (USD trillion)",
  "K_G" = "Green capital stock (USD trillion)",
  "K_C" = "Conventional capital stock (USD trillion)",
  "K" = "Capital stock (USD trillion)",
  "L_G" = "Green loans (USD trillion)",
  "L_C" = "Conventional loans (USD trillion)",
  "L" = "Total loans (USD trillion)",
  "BP" = "Profits of banks (USD trillion)",
  "EMIS_F" = "Fossil carbon emissions (GtCO2)",
  "CI" = "Carbon intensity (GtCO2 per USD trillion)",
  "Y_P" = "Potential output (USD trillion)",
  "u" = "Capacity utilisation rate",
  "g_Y" = "Growth rate of output",
  "lev" = "Leverage ratio",
  "g_D" = "Growth rate of deposits",
  "g_L" = "Growth rate of total loans",
  "g_LG" = "Growth rate of green loans",
  "g_LC" = "Growth rate of conventional loans",
  "g_K" = "Growth rate of capital stock",
  "g_KG" = "Growth rate of green capital stock",
  "g_KC" = "Growth rate of conventional capital stock",
  "g_YH" = "Growth rate of household income",
  "CO" = "Consumption expenditures (USD trillion)",
  "D_red" = "Deposits redundant (USD trillion)"
)
.par_descs <- list(
  "c_1" = "Propensity to consume out of disposable income",
  "c_2" = "Propensity to consume out of deposits",
  "int_C" = "Interest rate on conventional loans",
  "int_G" = "Interest rate on green loans",
  "int_D" = "Interest rate on deposits",
  "s_W" = "Wage share",
  "alpha_1" = "Sensitivity of the investment rate to the profit rate",
  "beta_1" = "Sensitivity of the green investment share to the interest rate differential",
  "beta_2" = "Sensitivity of the green investment share to the carbon tax",
  "beta_3" = "Sensitivity of the green investment share to the green subsidies",
  "tau_F" = "Firms' tax rate",
  "int_S" = "Interest rate on government securities",
  "pucf" = "Pre-tax unit cost of producing fossil energy (USD trillion/EJ)",
  "omega" = "CO2 intensity of fossil energy (GtCO2/EJ)",
  "c_CI" = "Green-to-conventional capital ratio at which carbon intensity takes its mean value",
  "k_CI" = "Steepness of carbon intensity improvement",
  "CI_max" = "Maximum potential value of carbon intensity",
  "CI_min" = "Minimum potential value of carbon intensity",
  "lambda" = "Parameter of households' portfolio choice",
  "s_F" = "Retention rate of firms",
  "alpha_0" = "Parameter related to autonomous investment",
  "gov_SUB" = "Share of green government subsidies",
  "tau_C" = "Carbon tax",
  "beta_0" = "Autonomous share of green investment in total investment",
  "tau_H" = "Households' tax rate",
  "gov_C" = "Share of government expenditure in output",
  "v" = "Capital productivity"
)
.var_srcs  <- list()
.par_srcs  <- list()
# ---------------------------------------------------------------------------

rm(list = ls(all = TRUE))
T <- 78; Start_year <- 2023; Scenarios <- 3

# -- Equations --
Equations <- function(t) {
#Households
Y_HG[t] <<- W[t]+DP[t]+BP[t]+int_D*D[t-1]+int_S*SEC_H[t-1] #Gross disposable income of households
W[t] <<- s_W*Y[t] #Wage income
Y_H[t] <<- Y_HG[t]-TAX_H[t] #Disposable income of households
CO_PRI[t] <<- c_1*Y_H[t-1]+c_2*V_H[t-1] #Private consumption expenditures
SEC_H[t] <<- lambda*V_H[t-1] #Government securities held by households
V_H[t] <<- SEC_H[t]+D[t] #Household wealth
D[t] <<- D[t-1]+Y_H[t]-CO_PRI[t]-(SEC_H[t]-SEC_H[t-1]) #Deposits #redundant
 
#Firms
Y[t] <<- CO_PRI[t]+I[t]+CO_GOV[t] #Nominal output
TP_G[t] <<- Y[t]-W[t]-int_C*L_C[t-1]-int_G*L_G[t-1] #Gross profits of firms
TP[t] <<- TP_G[t]-TAX_F[t]-TAX_C[t]+SUB[t] #Total profits of firms
RP[t] <<- s_F*TP[t] #Retained profits
DP[t] <<- TP[t]-RP[t] #Distributed profits
I[t] <<- (alpha_0+alpha_1*r[t-1])*K[t-1] #Investment
r[t] <<- TP[t]/K[t] #Rate of profit
I_G[t] <<- beta[t]*I[t] #Green investment
beta[t] <<- beta_0-beta_1*(int_G-int_C)+beta_2*tucf[t-1]+beta_3*gov_SUB #Share of green investment in total investment
tucf[t] <<- pucf+tau_C*omega #Total unit cost of fossil energy production
I_C[t] <<- I[t]-I_G[t] #Conventional investment
K_G[t] <<- K_G[t-1]+I_G[t] #Green capital stock
K_C[t] <<- K_C[t-1]+I_C[t] #Conventional capital stock
K[t] <<- K_C[t]+K_G[t] #Capital stock
L_G[t] <<- L_G[t-1]+I_G[t]-beta[t]*RP[t] #Green loans (USD trillion)
L_C[t] <<- L_C[t-1]+I_C[t]+I_G[t]-RP[t]-(L_G[t]-L_G[t-1]) #Conventional loans (USD trillion)
L[t] <<- L_C[t]+L_G[t] #Total loans (USD trillion)
 
#Banks
BP[t] <<- int_C*L_C[t-1]+int_G*L_G[t-1]+int_S*SEC_B[t-1]-int_D*D[t-1] #Profits of banks
SEC_B[t] <<- D[t]-L_G[t]-L_C[t] #Government securities held by banks
SEC_Bred[t] <<- SEC[t]-SEC_H[t] #Redundant government securities held by banks
 
#Government
SEC[t] <<- SEC[t-1]+int_S*SEC[t-1]-TAX[t]+SUB[t]+CO_GOV[t] #Government securities
CO_GOV[t] <<- gov_C*Y[t-1] #Government expenditure
SUB[t] <<- gov_SUB*I_G[t-1] #Green government subsidies
TAX_H[t] <<- tau_H*Y_HG[t-1] #Taxes on households
TAX_F[t] <<- tau_F*TP_G[t-1] #Taxes on firms' profits
TAX_C[t] <<- tau_C*EMIS_F[t-1] #Carbon tax revenues
TAX[t] <<- TAX_H[t]+TAX_F[t]+TAX_C[t] #Total taxes
 
#Emissions
EMIS_F[t] <<- CI[t]*Y[t] #Fossil carbon emissions
CI[t] <<- CI_min+(CI_max-CI_min)/(1+((K_G[t-1]/K_C[t-1])/c_CI)^k_CI) #Carbon intensity
 
#Auxiliary equations
Y_P[t] <<- v*K[t] #Potential output
u[t] <<- Y[t]/Y_P[t] #Capacity utilisation rate
g_Y[t] <<- (Y[t]-Y[t-1])/Y[t-1] #Growth rate of output
lev[t] <<- L[t]/K[t] #Leverage ratio
SEC_Y[t] <<- SEC[t]/Y[t] #Government securities-to-GDP ratio
#Supplementary growth equations
g_D[t] <<- (D[t]-D[t-1])/D[t-1] #Growth rate of deposits
g_L[t] <<- (L[t]-L[t-1])/L[t-1] #Growth rate of total loans
g_LG[t] <<- (L_G[t]-L_G[t-1])/L_G[t-1] #Growth rate of green loans
g_LC[t] <<- (L_C[t]-L_C[t-1])/L_C[t-1] #Growth rate of conventional loans
g_K[t] <<- (K[t]-K[t-1])/K[t-1] #Growth rate of capital stock
g_KG[t] <<- (K_G[t]-K_G[t-1])/K_G[t-1] #Growth rate of green capital stock
g_KC[t] <<- (K_C[t]-K_C[t-1])/K_C[t-1] #Growth rate of conventional capital stock
g_YH[t] <<- (Y_H[t]-Y_H[t-1])/Y_H[t-1] #Growth rate of disposable household income
g_YHG[t] <<- (Y_HG[t]-Y_HG[t-1])/Y_HG[t-1] #Growth rate of gross household income
g_IG[t] <<- (I_G[t]-I_G[t-1])/I_G[t-1] #Growth rate of green investment
g_TPG[t] <<- (TP_G[t]-TP_G[t-1])/TP_G[t-1] #Growth rate of gross profits
g_SECH[t] <<- (SEC_H[t]-SEC_H[t-1])/SEC_H[t-1] #Growth rate of household-held government securities
g_SECB[t] <<- (SEC_B[t]-SEC_B[t-1])/SEC_B[t-1] #Growth rate of bank-held government securities
g_SEC[t] <<- (SEC[t]-SEC[t-1])/SEC[t-1] #Growth rate of government securities
g_EMISF[t] <<- (EMIS_F[t]-EMIS_F[t-1])/EMIS_F[t-1] #Growth rate of emissions
g_VH[t] <<- (V_H[t]-V_H[t-1])/V_H[t-1] #Growth rate of household wealth
}

# -- Initial Values (generated) --
Parameters_InitialValues <- function() {

  # -- Free (set externally) --
  c_2 <<- 0.05  # free
  int_C <<- 0.09  # free
  int_G <<- 0.09  # free
  int_D <<- 0.04  # free
  s_W <<- 0.55  # free
  alpha_1 <<- 0.1  # free
  beta_1 <<- 1  # free
  beta_2 <<- 20  # free
  beta_3 <<- 1  # free
  tau_F <<- 0.15  # free
  int_S <<- 0.0254  # free
  pucf <<- 0.021  # free
  omega <<- 0.072  # free
  Y[1] <<- 106.94  # free
  I[1] <<- 0.259*Y[1]  # free
  L[1] <<- 0.93*Y[1]  # free
  u[1] <<- 0.73  # free
  I_G[1] <<- 1.78  # free
  EMIS_F[1] <<- 37.82  # free
  D[1] <<- 130  # free
  SUB[1] <<- 0.14  # free
  CO_GOV[1] <<- 0.17*Y[1]  # free
  SEC[1] <<- 0.94*Y[1]  # free
  TAX_C[1] <<- 0.104  # free
  g_Y[1] <<- 0.029  # free
  g_D[1] <<- g_Y[1]  # free
  g_L[1] <<- g_Y[1]  # free
  g_K[1] <<- g_Y[1]  # free
  g_YH[1] <<- g_Y[1]  # free
  g_LG[1] <<- g_Y[1]  # free
  g_LC[1] <<- g_Y[1]  # free
  g_KG[1] <<- g_Y[1]  # free
  g_KC[1] <<- g_Y[1]  # free
  g_IG[1] <<- g_Y[1]  # free
  g_TPG[1] <<- g_Y[1]  # free
  g_YHG[1] <<- g_Y[1]  # free
  g_SECH[1] <<- g_Y[1]  # free
  g_SECB[1] <<- g_Y[1]  # free
  g_SEC[1] <<- g_Y[1]  # free
  g_VH[1] <<- g_Y[1]  # free
  g_EMISF[1] <<- g_Y[1]  # free
  CI_2050 <<- 0.8*CI[1]  # free
  KG_KC2049 <<- K_G[1]/K_C[1]+26*0.01  # free
  CI_max <<- 1.2*CI[1]  # free
  CI_min <<- 0.5*CI[1]  # free
  k_CI <<- (log((1/((CI_2050-CI_min)/(CI_max-CI_min)))-1)-log((1/((CI[1]-CI_min)/(CI_max-CI_min)))-1))/(log(KG_KC2049)-log((K_G[1]/(1+g_KG[1]))/(K_C[1]/(1+g_KC[1]))))  # free
  SEC_Bred[1] <<- SEC_B[1]  # free

  # -- Model-constrained (solved in dependency order) --
  c_CI <<- (K_G[1]/K_C[1]) / ((CI_max-CI_min)/(CI[1]-CI_min) - 1)^(1/k_CI)  #Calculated using Eq. (CI)
  W[1] <<- s_W*Y[1]  #Calculated using Eq. (W)
  CO_PRI[1] <<- (Y[1] -  (I[1]) -  (CO_GOV[1]))  #Calculated using Eq. (Y)
  SEC_H[1] <<- (- SEC_Bred[1] + SEC[1])  #Calculated using Eq. (SEC_Bred)
  V_H[1] <<- SEC_H[1]+D[1]  #Calculated using Eq. (V_H)
  beta[1] <<- (I_G[1]) / (I[1])  #Calculated using Eq. (I_G)
  I_C[1] <<- I[1]-I_G[1]  #Calculated using Eq. (I_C)
  K_G[1] <<- I_G[1] / (1 - (1 / ((1 + g_KG[1]))))  #Calculated using Eq. (K_G)
  K_C[1] <<- I_C[1] / (1 - (1 / ((1 + g_KC[1]))))  #Calculated using Eq. (K_C)
  K[1] <<- K_C[1]+K_G[1]  #Calculated using Eq. (K)
  TAX[1] <<- (- SEC[1] + (SEC[1] / (1 + g_SEC[1])) + int_S*(SEC[1] / (1 + g_SEC[1])) + SUB[1] + CO_GOV[1])  #Calculated using Eq. (SEC)
  CI[1] <<- (EMIS_F[1]) / (Y[1])  #Calculated using Eq. (EMIS_F)
  Y_P[1] <<- (Y[1]) / (u[1])  #Calculated using Eq. (u)
  lev[1] <<- L[1]/K[1]  #Calculated using Eq. (lev)
  SEC_Y[1] <<- SEC[1]/Y[1]  #Calculated using Eq. (SEC_Y)
  lambda <<- (SEC_H[1]) / ((V_H[1] / (1 + g_VH[1])))  #Calculated using Eq. (SEC_H)
  gov_SUB <<- (SUB[1]) / ((I_G[1] / (1 + g_IG[1])))  #Calculated using Eq. (SUB)
  tau_C <<- (TAX_C[1]) / ((EMIS_F[1] / (1 + g_EMISF[1])))  #Calculated using Eq. (TAX_C)
  tucf[1] <<- pucf+tau_C*omega  #Calculated using Eq. (tucf)
  beta_0 <<- (beta[1] + (beta_1*(int_G-int_C)) -  (beta_2*tucf[1]) -  (beta_3*gov_SUB))  #Calculated using Eq. (beta)
  gov_C <<- (CO_GOV[1]) / ((Y[1] / (1 + g_Y[1])))  #Calculated using Eq. (CO_GOV)
  v <<- (Y_P[1]) / (K[1])  #Calculated using Eq. (Y_P)
  c_1 <<- (CO_PRI[1] -  (c_2*(V_H[1] / (1 + g_VH[1])))) / ((Y_H[1] / (1 + g_YH[1])))  #Calculated using Eq. (CO_PRI)
  s_F <<- (RP[1]) / (TP[1])  #Calculated using Eq. (RP)
  DP[1] <<- 8.8188  #Calculated using Eq. (DP (block solve))
  TP[1] <<- 33.7134  #Calculated using Eq. (TP (block solve))
  RP[1] <<- 24.8946  #Calculated using Eq. (L_G (block solve))
  TP_G[1] <<- 39.4244  #Calculated using Eq. (TP_G (block solve))
  TAX_F[1] <<- 5.747  #Calculated using Eq. (TAX_F (block solve))
  L_G[1] <<- 6.3915  #Calculated using Eq. (L_C (block solve))
  L_C[1] <<- 93.0627  #Calculated using Eq. (L (block solve))
  r[1] <<- TP[1]/K[1]  #Calculated using Eq. (r)
  SEC_B[1] <<- D[1]-L_G[1]-L_C[1]  #Calculated using Eq. (SEC_B)
  BP[1] <<- int_C*(L_C[1] / (1 + g_LC[1]))+int_G*(L_G[1] / (1 + g_LG[1]))+int_S*(SEC_B[1] / (1 + g_SECB[1]))-int_D*(D[1] / (1 + g_D[1]))  #Calculated using Eq. (BP)
  Y_HG[1] <<- W[1]+DP[1]+BP[1]+int_D*(D[1] / (1 + g_D[1]))+int_S*(SEC_H[1] / (1 + g_SECH[1]))  #Calculated using Eq. (Y_HG)
  TAX_H[1] <<- (TAX[1] -  (TAX_F[1]) -  (TAX_C[1]))  #Calculated using Eq. (TAX)
  Y_H[1] <<- Y_HG[1]-TAX_H[1]  #Calculated using Eq. (Y_H)
  alpha_0 <<- (I[1]) / ((K[1] / (1 + g_K[1]))) - (alpha_1*r[1])  #Calculated using Eq. (I)
  tau_H <<- (TAX_H[1]) / ((Y_HG[1] / (1 + g_YHG[1])))  #Calculated using Eq. (TAX_H)
}

# -- Scenarios --
# -- Scenario 1: Baseline --
Parameters_scenario1 <- function() {
}

# -- Scenario 2: Green investment shock --
Parameters_scenario2 <- function() {
  int_G <<- 0.06
int_C <<- 0.10
beta_0 <<- 0.33
}

# -- Scenario 3: Degrowth shock --
Parameters_scenario3 <- function() {
  c_1 <<- 0.7
alpha_0 <<- 0.02
}
eq_body <- deparse(body(Equations))
var_names <- unique(na.omit(sub('^\\s*([A-Za-z_][A-Za-z0-9_]*)\\[t\\]\\s*<<-.*','\\1',
  eq_body[grepl('\\[t\\]\\s*<<-', eq_body)])))
Symbols_var      <- var_names
Symbols_var_sort <- sort(var_names)
iv_body  <- deparse(body(Parameters_InitialValues))
iv_vars  <- unique(na.omit(sub('^\\s*([A-Za-z_][A-Za-z0-9_]*)\\[1\\]\\s*<<-.*','\\1',
  iv_body[grepl('\\[1\\]\\s*<<-', iv_body)])))
par_names <- setdiff(iv_vars, var_names)
Symbols_par_sort <- sort(par_names)
all_vars <- unique(c(var_names, iv_vars))
genv <- globalenv()
ensure_vectors <- function() {
  for (v in all_vars) {
    cur <- if (exists(v, envir=genv, inherits=FALSE)) get(v, envir=genv) else NULL
    if (is.null(cur) || !is.numeric(cur) || length(cur) != T) {
      vec <- vector('numeric', length=T)
      if (!is.null(cur) && is.numeric(cur) && length(cur)>=1)
        vec[seq_len(min(length(cur),T))] <- cur[seq_len(min(length(cur),T))]
      assign(v, vec, envir=genv)
    }
  }
}
results <- list()
for (j in 1:3) {
  for (v in all_vars) assign(v, vector('numeric', length = T), envir=genv)
  for (iterations in 1:30) {Parameters_InitialValues()}
  ensure_vectors()
  for (i in 2:T) {
    if (j==2 & i>=5) {Parameters_scenario2()}
    if (j==3 & i>=5) {Parameters_scenario3()}
    for (iterations in 1:30) {Equations(t=i)}
  }
  results[[j]] <- as.data.frame(setNames(
    lapply(var_names, function(v) get(v, envir=genv, inherits=FALSE)),
    var_names))
  # -- Tables (equation order) --
  tablename <- paste0('Variables', j)
  values <- setNames(data.frame(matrix(ncol=length(Symbols_var), nrow=T)), Symbols_var)
  for (v in seq_along(Symbols_var)) values[,v] <- get(Symbols_var[v], envir=genv, inherits=FALSE)
  assign(tablename, round(values, 4))
  # -- Tables (alphabetical order) --
  tablename <- paste0('Variables_sorted', j)
  values <- setNames(data.frame(matrix(ncol=length(Symbols_var_sort), nrow=T)), Symbols_var_sort)
  for (v in seq_along(Symbols_var_sort)) values[,v] <- get(Symbols_var_sort[v], envir=genv, inherits=FALSE)
  assign(tablename, round(values, 6))
  # -- Parameter table --
  tablename <- paste0('Parameters_sorted', j)
  values <- setNames(data.frame(matrix(ncol=length(Symbols_par_sort), nrow=1)), Symbols_par_sort)
  for (v in seq_along(Symbols_par_sort)) {
    val <- tryCatch(get(Symbols_par_sort[v], envir=genv, inherits=FALSE), error=function(e) NA)
    values[,v] <- if (length(val)==1) val else val[1]
  }
  assign(tablename, round(values, 4))
  rm(values)
  # -- Save CSV files --
  write.csv(get(paste0('Variables',j)),        paste0('Variables',j,'.csv'))
  write.csv(get(paste0('Variables_sorted',j)), paste0('Variables-sorted',j,'.csv'))
  write.csv(get(paste0('Parameters_sorted',j)),paste0('Parameters-sorted',j,'.csv'))
  cat('Scenario', j, 'done\n')
}

# -- Charts --
if (!requireNamespace('ggplot2', quietly=TRUE)) install.packages('ggplot2')
library(ggplot2)
years      <- 2023 + seq_len(T) - 1
sc_names   <- c("Baseline", "Green investment shock", "Degrowth shock")
chart_cols <- c("#000000","#009E73","#D55E00")
chart_lts  <- c("solid","solid","solid")
Chart3 <- function(fig_title, variable, label, min, max,
                   sce1=1, sce2=2, sce3=3, legend_x=0.25, legend_y=0.92) {
  sc_sel <- c(sce1, sce2, sce3)
  df <- do.call(rbind, lapply(sc_sel, function(j) {
    data.frame(Year=years, Value=results[[j]][[variable]],
               Scenario=sc_names[j], stringsAsFactors=FALSE)
  }))
  df$Scenario <- factor(df$Scenario, levels=sc_names[sc_sel])
  # DEFINE interface style (matches interface.R theme_define)
  define_theme <- theme_bw(base_size=7, base_family='Helvetica') %+replace%
    theme(
      panel.background  = element_rect(fill='white',    colour=NA),
      panel.border      = element_rect(colour='#2C3E4A', fill=NA, linewidth=0.45),
      plot.background   = element_rect(fill='white',    colour=NA),
      panel.grid.major  = element_line(colour='#EAECEE', linewidth=0.25),
      panel.grid.minor  = element_blank(),
      axis.ticks        = element_line(colour='#2C3E4A', linewidth=0.3),
      axis.ticks.length = unit(-2.5, 'pt'),
      axis.text.x       = element_text(colour='#2C3E4A', size=6,  margin=margin(t=4)),
      axis.text.y       = element_text(colour='#2C3E4A', size=6,  margin=margin(r=4)),
      axis.title.x      = element_text(colour='#2C3E4A', size=5.5, margin=margin(t=4)),
      axis.title.y      = element_text(colour='#2C3E4A', size=5.5, angle=90, margin=margin(r=4)),
      plot.title        = element_text(colour='#2E8B57', size=7,  face='bold', hjust=0, margin=margin(b=3)),
      legend.position   = 'bottom',
      legend.direction  = 'horizontal',
      legend.background = element_rect(fill='white', colour=NA),
      legend.key        = element_rect(fill=NA, colour=NA),
      legend.key.width  = unit(16, 'pt'),
      legend.key.height = unit(5,  'pt'),
      legend.text       = element_text(size=5.5, colour='#2C3E4A'),
      legend.title      = element_blank(),
      legend.spacing.x  = unit(3, 'pt'),
      legend.margin     = margin(t=2, b=1),
      plot.margin       = margin(5, 8, 4, 5)
    )
  p <- ggplot(df, aes(x=Year, y=Value, colour=Scenario, linetype=Scenario, group=Scenario)) +
    geom_line(linewidth=0.6, lineend='round', na.rm=TRUE) +
    scale_colour_manual(values=chart_cols[sc_sel]) +
    scale_linetype_manual(values=chart_lts[sc_sel]) +
    scale_y_continuous(limits=c(min, max), expand=expansion(mult=c(0.04, 0.06))) +
    scale_x_continuous(expand=expansion(mult=c(0.01, 0.02))) +
    labs(title=variable, y=label, x='Year') +
    define_theme +
    guides(colour=guide_legend(nrow=2, byrow=TRUE, override.aes=list(linewidth=0.9)))
  ggsave(fig_title, p, width=3.5, height=2.5, dpi=300, units='in')
  invisible(p)
}
Chart3(fig_title="Fig1-Leverage.jpeg", variable='lev', label="Firm leverage", min=0, max=0, sce1=1, sce2=2, sce3=3, legend_x=0.25, legend_y=0.92)
Chart3(fig_title="Fig2-Growth.jpeg", variable='g_Y', label="Growth rate of output", min=0, max=0, sce1=1, sce2=2, sce3=3, legend_x=0.25, legend_y=0.92)
Chart3(fig_title="Fig3-Output.jpeg", variable='Y', label="Output (trillion USD)", min=0, max=0, sce1=1, sce2=2, sce3=3, legend_x=0.25, legend_y=0.92)
Chart3(fig_title="Fig4-Profit-rate.jpeg", variable='r', label="Rate of profit", min=0, max=0, sce1=1, sce2=2, sce3=3, legend_x=0.25, legend_y=0.92)
Chart3(fig_title="Fig5-Share-of-green-investment.jpeg", variable='beta', label="Share of green investment", min=0, max=0, sce1=1, sce2=2, sce3=3, legend_x=0.25, legend_y=0.92)
Chart3(fig_title="Fig6-Carbon-intensity.jpeg", variable='CI', label=expression("CO"[2]*" intensity"), min=0, max=0, sce1=1, sce2=2, sce3=3, legend_x=0.25, legend_y=0.92)
Chart3(fig_title="Fig7-Emissions.jpeg", variable='EMIS_F', label=expression("Fossil CO"[2]*" emissions (Gt)"), min=0, max=0, sce1=1, sce2=2, sce3=3, legend_x=0.25, legend_y=0.92)

# -- Your analysis starts here --
